/* eslint-disable */
/** Declaration file generated by dts-gen */

export = redis_parser;

declare class redis_parser {
    constructor(...args: any[]);

    execute(...args: any[]): void;

    reset(...args: any[]): void;

    setReturnBuffers(...args: any[]): void;

    setStringNumbers(...args: any[]): void;

}

